apiVersion: v1
kind: Service
metadata:
  name: kafka-0
spec:
  ports:
  - port: 9092
  clusterIP: None
---
apiVersion: v1
kind: Endpoints
metadata:
  name: kafka-0
subsets:
- addresses:
  - ip: 192.168.5.49
  #- ip: 35.234.30.92
  #- ip: 104.199.179.26
  # - ip: 192.168.5.218
  ports:
  - port: 9092
---
